type Binary = 0 | 1;

export type ModelData = {
  count_floors_pre_eq: number;
  age_building: number;
  has_superstructure_adobe_mud: Binary;
  has_superstructure_mud_mortar_stone: Binary;
  has_superstructure_stone_flag: Binary;
  has_superstructure_cement_mortar_stone: Binary;
  has_superstructure_mud_mortar_brick: Binary;
  has_superstructure_cement_mortar_brick: Binary;
  has_superstructure_timber: Binary;
  has_superstructure_bamboo: Binary;
  has_superstructure_rc_non_engineered: Binary;
  has_superstructure_rc_engineered: Binary;
  has_superstructure_other: Binary;
  height_plinth_ratio: number;
  has_geotechnical_risk: number;
  "foundation_type_Bamboo/Timber": Binary;
  "foundation_type_Cement-Stone/Brick": Binary;
  "foundation_type_Mud mortar-Stone/Brick": Binary;
  foundation_type_Other: Binary;
  foundation_type_RC: Binary;
  "roof_type_Bamboo/Timber": Binary;
  "roof_type_RCC/RB/RBC": Binary;
  "ground_floor_type_Brick/Stone": Binary;
  ground_floor_type_Mud: Binary;
  ground_floor_type_Other: Binary;
  ground_floor_type_RC: Binary;
  ground_floor_type_Timber: Binary;
  "other_floor_type_Not applicable": Binary;
  "other_floor_type_RCC/RB/RBC": Binary;
  "other_floor_type_TImber/Bamboo-Mud": Binary;
  "other_floor_type_Timber-Planck": Binary;
  "position_Attached-1 side": Binary;
  "position_Attached-2 side": Binary;
  "position_Attached-3 side": Binary;
  "position_Not attached": Binary;
};

export type ModelResult = {
  feature_importance: {
    age_building: number;
    count_floors_pre_eq: number;
    foundation_type_Bamboo_Timber: number;
    foundation_type_Cement_Stone_Brick: number;
    foundation_type_Mud_mortar_Stone_Brick: number;
    foundation_type_Other: number;
    foundation_type_RC: number;
    ground_floor_type_Brick_Stone: number;
    ground_floor_type_Mud: number;
    ground_floor_type_Other: number;
    ground_floor_type_RC: number;
    ground_floor_type_Timber: number;
    has_geotechnical_risk: number;
    has_superstructure_adobe_mud: number;
    has_superstructure_bamboo: number;
    has_superstructure_cement_mortar_brick: number;
    has_superstructure_cement_mortar_stone: number;
    has_superstructure_mud_mortar_brick: number;
    has_superstructure_mud_mortar_stone: number;
    has_superstructure_other: number;
    has_superstructure_rc_engineered: number;
    has_superstructure_rc_non_engineered: number;
    has_superstructure_stone_flag: number;
    has_superstructure_timber: number;
    height_plinth_ratio: number;
    other_floor_type_Not_applicable: number;
    other_floor_type_RCC_RB_RBC: number;
    other_floor_type_TImber_Bamboo_Mud: number;
    other_floor_type_Timber_Planck: number;
    position_Attached_1_side: number;
    position_Attached_2_side: number;
    position_Attached_3_side: number;
    position_Not_attached: number;
    roof_type_Bamboo_Timber: number;
    roof_type_RCC_RB_RBC: number;
  };
  prediction: [[number, number, number]];
};
