type Binary = 0 | 1;

export type ModelData = {
  count_floors_pre_eq: number;
  age_building: number;
  has_superstructure_adobe_mud: Binary;
  has_superstructure_mud_mortar_stone: Binary;
  has_superstructure_stone_flag: Binary;
  has_superstructure_cement_mortar_stone: Binary;
  has_superstructure_mud_mortar_brick: Binary;
  has_superstructure_cement_mortar_brick: Binary;
  has_superstructure_timber: Binary;
  has_superstructure_bamboo: Binary;
  has_superstructure_rc_non_engineered: Binary;
  has_superstructure_rc_engineered: Binary;
  has_superstructure_other: Binary;
  height_plinth_ratio: number;
  geotechnical_risk: number;
  "foundation_type_Bamboo/Timber": Binary;
  "foundation_type_Cement-Stone/Brick": Binary;
  "foundation_type_Mud mortar-Stone/Brick": Binary;
  foundation_type_Other: Binary;
  foundation_type_RC: Binary;
  "roof_type_Bamboo/Timber": Binary;
  "roof_type_RCC/RB/RBC": Binary;
  "ground_floor_type_Brick/Stone": Binary;
  ground_floor_type_Mud: Binary;
  ground_floor_type_Other: Binary;
  ground_floor_type_RC: Binary;
  ground_floor_type_Timber: Binary;
  "other_floor_type_Not applicable": Binary;
  "other_floor_type_RCC/RB/RBC": Binary;
  "other_floor_type_TImber/Bamboo-Mud": Binary;
  "other_floor_type_Timber-Planck": Binary;
  "position_Attached-1 side": Binary;
  "position_Attached-2 side": Binary;
  "position_Attached-3 side": Binary;
  "position_Not attached": Binary;
};
